name: ItemSage
version: '${project.version}'
main: it.giopav.itemsage.ItemSage
api-version: 1.19
authors: [ Giopav ]
description: The Item Sage helps you get a glimpse of everything.
commands:
  isage:
    description: Your description
    usage: §cType /<command> help for a hint.
    permission: yourplugin.yourcommandpermission